#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : geebook  # The title of the book. Will be placed in the left navbar.
author                      : Qiusheng Wu  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

#######################################################################################
# HTML-specific settings
html:
  baseurl                   : "https://book.geemap.org/"  # The base URL where your book will be hosted.